gui:
  nerdFontsVersion: "3"
  commitAuthorShortLength: 5
  authorColors:
    dalailahner: red
  branchColors:
    main: red
  theme:
    activeBorderColor:
      - red
      - bold
    selectedLineBgColor:
      - red
keybinding:
  universal:
    suspendApp: <disabled>
    undo: <c-z>
    copyPullRequestURL: <disabled>
    redo: <c-y>
