# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# : Manager {{{

[mgr]

cwd = { fg = "darkgray" }

# Hovered
hovered = { fg = "white", bg = "red" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "white", bold = true, italic = true }
find_position = { fg = "red", bg = "white", italic = true }

# Marker
marker_copied = { fg = "white", bg = "green" }
marker_cut = { fg = "white", bg = "red" }
marker_marked = { fg = "white", bg = "blue" }
marker_selected = { fg = "white", bg = "white" }

# : }}}


# : Tabs {{{

[tabs]

active = { fg = "white", bg = "red" }
inactive = { fg = "white", bg = "darkgray" }

# : }}}


# : Mode {{{

[mode]
normal_main = { fg = "white", bg = "red", bold = true }
normal_alt = { fg = "red", bg = "white" }

# Select mode
select_main = { fg = "white", bg = "green", bold = true }
select_alt = { fg = "green", bg = "white" }

# Unset mode
unset_main = { fg = "black", bg = "yellow", bold = true }
unset_alt = { fg = "yellow", bg = "white" }

# : }}}


# : Status bar {{{

[status]
overall   = { fg = "white", bg = "black" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_type = { fg = "white" }
perm_read = { fg = "yellow" }
perm_write = { fg = "red" }
perm_exec = { fg = "#df7020" }
perm_sep = { fg = "darkgray" }

# Progress
progress_label = { fg = "darkgray", bold = true , bg = "white" }
progress_normal = { fg = "black", bg = "white" }
progress_error = { fg = "black", bg = "red" }

# : }}}


# : Which {{{

[which]
mask = { bg = "black" }
cand = { fg = "cyan" }
rest = { fg = "blue" }
desc = { fg = "red" }
separator = "  "
separator_style = { fg = "red" }

# : }}}


# : Picker {{{

[pick]
border = { fg = "red" }
active = { fg = "red" }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "red" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "red" }
title = {}
hovered = { underline = true }

# : }}}


# : Help {{{

[help]
on = { fg = "white" }
run = { fg = "white" }
desc = { fg = "white" }
hovered = { fg = "white", bg = "red", bold = true }
footer = { fg = "white", bg = "darkgray" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	
	# Images
	{ mime = "image/*", fg = "yellow" },

	# Videos
	{ mime = "video/*", fg = "yellow" },

	# Audio
	{ mime = "audio/*", fg = "blue" },

	# Archives
	{ mime = "application/{,g}zip", fg = "darkgray", bold = true },
	{ mime = "application/{tar,bzip*,7z-compressed,xz,rar}", fg = "darkgray", bold = true },

	# Link
	{ name = "*", is = "link", fg = "cyan", underline = true },

	# Orphan
	{ name = "*", is = "orphan", fg = "white", bg = "red", bold = true },

	# FIFO
	{ name = "*", is = "fifo", fg = "yellow", bg = "black" },

	# Socket
	{ name = "*", is = "sock", fg = "magenta", bold = true },

	# Block device
	{ name = "*", is = "block", fg = "red", bg = "black", bold = true },

	# Char device
	{ name = "*", is = "char", fg = "red", bg = "black", bold = true },

	# Exectuable
	{ name = "*", is = "exec", fg = "red", bold = true },

	# Sticky
	{ name = "*", is = "sticky", fg = "black", bg = "green" },
	
	# Directory
	{ name = "*/", fg = "green", bold = true },

]
