# dalailahner theme for Kitty

## name: dalailahner
## author: dalailahner
## license: GLWTS
## blurb: dark color theme with a sultry red for the kitty terminal

# special
foreground            #d9d9d9
background            #232323
cursor                #d9d9d9
selection_foreground  #e5e5e5
selection_background  #cd231d
url_color             #5a80f2
active_border_color   #cd231d
inactive_border_color #dfbf20

# black
color0    #1c1c1c
color8    #4c4c4c

# red
color1    #cd231d
color9    #cd231d

# green
color2    #4dcb58
color10   #4dcb58

# yellow
color3    #dfbf20
color11   #dfbf20

# blue
color4    #5a80f2
color12   #5a80f2

# magenta
color5    #e64cb2
color13   #e64cb2

# cyan
color6    #52e0e0
color14   #52e0e0

# white
color7    #d9d9d9
color15   #e5e5e5
